### PR TITLE
Allow following system theme for night mode

### PR DESCRIPTION
**Pull request by StephenBrown2**
Implementation adding System Follow support for Dark mode as per comment: https://github.com/nightscout/AndroidAPS/pull/326#issuecomment-777716357

### CODE REVIEW

**Comment by osodebailar** [comment]
get following failure after checkout build and start on simulation:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: info.nightscout.androidaps, PID: 31169
    java.lang.RuntimeException: Unable to create application info.nightscout.androidaps.MainApp: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:302)
        at info.nightscout.androidaps.utils.sharedPreferences.SPImplementation.getString(SPImplementation.kt:32)
        at info.nightscout.androidaps.MainApp.selectThemeMode(MainApp.kt:90)
        at info.nightscout.androidaps.MainApp.onCreate(MainApp.kt:72)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by StephenBrown2** [comment]
Interesting, I'm running this build on my Pixel 5 at this moment. I didn't try running it in an emulator. I'd imagine there's an issue with your checkout, or cached preferences? I did not change the name of the preference, but I did change the value to be a string instead of a boolean.

**Comment by StephenBrown2** [comment]
I ran through the app setup in the emulator and found that the setting didn't match the actual default given in selectThemeMode and switchTheme, so the selection didn't match on first look. However, it did not crash for me, even in the emulator.

**Comment by osodebailar** [comment]
@StephenBrown2 in addition we need the ability to follow the system mode automatic . 
So when in Android setting the dark mode is switched off or on , aaps has to follow the mode. 
Can you work on this feature ?

**Comment by StephenBrown2** [comment]
That is exactly what this PR enables. There is now a "Use Device theme" option, which will follow the system dark mode setting.

**Comment by osodebailar** [comment]
@StephenBrown2  it works in simulation in Android 10 but not on a pixel5 with Android 11.

**Comment by StephenBrown2** [comment]
Like my Pixel 5 running Android 11?
[Screen Recording](https://photos.app.goo.gl/274RfWyHsjRmu2mT6)

**Comment by osodebailar** [comment]
@StephenBrown2  if i change in android system settings manual to dark or light, aaps doe not follow. 
if i set the settings in aaps to follow system, the theme is always in dark mode.
you have actual checkout my branch ? maybe you can test it

**Comment by osodebailar** [comment]
@StephenBrown2  i think i solved it. can you test it on my branch ?

**Comment by StephenBrown2** [comment]
I've been offline for the past couple days.
Will try to test your branch this weekend or next week.

**Comment by StephenBrown2** [comment]
Looks like you changed several things from my PR that may have broke things. Though in testing I couldn't replicated, I've suggested several changes that should clean things up a little.

**Comment by osodebailar** [comment]
For me its Running now Perfect with my changes .
If you Think we Can do it better, i think a new Branch for merge request is the best thing

**Pull request merged**
